### PR TITLE
feat: keep track of block and indexer cursor

### PR DESCRIPTION
**Pull request by Jemiiah**
- [x] issue #93
- [x] follows contribution  guide (https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [x] code change includes tests
- [x] breaking change

 addresses the issue of persisting that the user ID accross containers restarts

### CODE REVIEW

**Comment by b-j-roberts** [comment]
When I try and run `docker compose up` after restarting and using these changes, I get 
```
indexer-1   | error: the following required arguments were not provided:
indexer-1   |   --sink-id <SINK_ID>
indexer-1   |
indexer-1   | Usage: apibara-sink-webhook run --sink-id <SINK_ID> --allow-env <ALLOW_ENV> --allow-env-from-env <ALLOW_ENV_FROM_ENV> --persist-to-redis <PERSIST_TO_REDIS> <SCRIPT>
```

And the indexer never starts. Were you able to get this working?

**Comment by Jemiiah** [comment]
okay let me look at it again and try resolve the issue

**Comment by b-j-roberts** [comment]
I made the changes needed to get this working because I need this for my production deployment asap.

**Comment by Jemiiah** [comment]
Okay thank you for the opportunity Robert, hope to work with you on the long run  🚀

**Pull request merged**
