### PR TITLE
feat: create an Unruggable Meme quest

### PR DESCRIPTION
**Pull request by TAdev0**
- [x] issue #28 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests
- [x] breaking change

### CODE REVIEW

**Comment by TAdev0** [comment]
@b-j-roberts  hi, this is a first draft, no test for now. Can you review it before i add test to make sure i did what is correct?

**Comment by TAdev0** [comment]
Note that the checks consist of :
- `owner` check to make sure the user is the owner of the memecoin
- `is_launched` to make sure it is indeed a Unruggable memecoin that implements this function

Note that it is still possible to create a contract with these 2 functions only and pass the quest

**Comment by TAdev0** [comment]
I removed the `daily_quest` because i guess this is a quest you do only one time so its not daily, right?

**Comment by TAdev0** [comment]
@b-j-roberts  i just added tests : 

- `deploy_unruggable_quest_main` and `deploy_unruggable_mock` for setup
- `deploy_unruggable_quest_test` to check for good deployment of the unruggable quest as the only main quest, without daily quests
- `unruggable_quest_test`  to check that the quest can be completed by a user that deployed a contract that matches `is_launched` and `owner` from unruggable interface

**Review by b-j-roberts — APPROVED** [review]
Great work, as always!

I don't think there is a perfect way for now to stop people from creating fake unruggable memecoin contracts that match the interfaces we check for now, so I think this is sufficient.

**Comment by TAdev0** [comment]
great, perfect!

**Pull request merged**
