### PR TITLE
added feat: Quest progress bar

### PR DESCRIPTION
**Pull request by KeneePatel**
- [x] issue #175 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests
- [ ] breaking change

Adds a prop for `progress` which is inclusive [0,4] where 0 is for no progress and 4 is for claimable. Have made to change the background-color from hue 0 (red) to hue 60 (yellow) for progress 0 -> 4. Also, the button pulsates when `progress` will be 4. closes Issue #175 

I did not find any need for `needed`, but let me know what it will be used for or if there will be any TODO on it. I will be happy to take it :)

### CODE REVIEW

**Comment by martinvibes** [comment]
let me hop on this

**Comment by martinvibes** [comment]
let me hop on this @KeneePatel

**Comment by KeneePatel** [comment]
Dear @martinvibes,

It's already complete. If you take a second and look above, there's a PR that relates to this issue. 😅

**Review by b-j-roberts — COMMENTED** [review]
Nice work so far, and thanks for the quick turn around!

You'll need to use the `needed` field, because `progress` wont always go from 0-4, but it will go from 0-`needed`. So for instance, what you created would work for `needed=4`, but if `needed=6`, there would be 6 steps for progress.

Hope that clears things up.

**Comment by KeneePatel** [comment]
thanks for the review, I understand what you are trying to communicate and will do the reviewed change and get back quickly.

**Comment by b-j-roberts** [comment]
Also, I think the progress bar should fill up from the left. Here is an image of the general idea I was looking for:
image

**Comment by b-j-roberts** [comment]
There should be `needed` steps, not always 4. So if `needed=6` for example, there would be 6 different increments not 4

**Comment by KeneePatel** [comment]
@b-j-roberts thanks for the clear directions, it really helped.

Just pushed the commit to make the progress bar width and the color of button dynamic. Have a look and please feel free to mention any required change. I will be happy to improve the code.

**Comment by b-j-roberts** [comment]
Nice work, I appreciate it.

**Pull request merged**
