### PR TITLE
[feat] Deposit reward when adding new template

### LINKED ISSUE #30: [feat] Template ERC20 rewards deposit
Add the functionality to deposit the `reward` from the `reward_token` in the `add_template` function call. Make sure to revert if the deposit fails at any step.

#### References
- [Template add_template func](https://github.com/keep-starknet-strange/art-peace/blob/5d71f79a5fc1a7fbfd758bc2646d9e26c48f5cfb/onchain/src/templates/component.cairo#L55)
- [ERC20 deposit example](https://github.com/keep-starknet-strange/succinct-starknet/blob/11b2139427a34b5aaf764eab4db77942e8b5fb60/src/fee_vault.cairo#L144)

### PR DESCRIPTION
**Pull request by TAdev0**
- [x] issue #30 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/art-peace/blob/main/CONTRIBUTING.md)
- [x] code change includes tests
- [ ] breaking change

Resolves #30

### CODE REVIEW

**Comment by TAdev0** [comment]
@b-j-roberts  here is a first draft.

Tests dont pass for now beause we need to deploy some mock erc20 contract in test to make the transfer work.

Can you give me more precisions, is anyone allowed to call `add_template` ? Should I add storage variables to keep track of template ids -> reward amount / reward token ?

**Comment by b-j-roberts** [comment]
> Can you give me more precisions, is anyone allowed to call `add_template` ? Should I add storage variables to keep track of template ids -> reward amount / reward token ?

Yes, anyone can call `add_template` no changes are needed other than depositing the reward token.
`reward` and `reward_token` are already defined within the `TemplateMetadata`, so there is no need to add extra variables or storage.

**Comment by b-j-roberts** [comment]
> Tests dont pass for now beause we need to deploy some mock erc20 contract in test to make the transfer work.

If you don't mind doing that as part of this PR, here is a decent `ERC20` mock from another project. https://github.com/keep-starknet-strange/succinct-starknet/blob/main/src/mocks/erc20_mock.cairo

**Comment by TAdev0** [comment]
@b-j-roberts  sure i'll add test , was just waiting for precisions before implementing them

**Pull request closed without merging**
