### PR TITLE
[feat]: Add unit tests to all quests

### PR DESCRIPTION
**Pull request by TAdev0**
@b-j-roberts as discussed, here are a bunch of `should_panic` tests that make sure its not possible to extra claim at some point for quests.

### CODE REVIEW

**Comment by TAdev0** [comment]
@b-j-roberts  ready for review!

**Comment by mubarak23** [comment]
@TAdev0 please kindly drop your telegram handle, i want to ask you some question regarding writing test for quest on art peace

**Comment by TAdev0** [comment]
@mubarak23  sure ,its @TAdev0

**Comment by b-j-roberts** [comment]
Thanks!

**Comment by mubarak23** [comment]
Should all test for quest contract have this functions

**Pull request merged**
